### ISSUE TITLE
Determine the Linux Distro

### ISSUE THREAD

**Issue by melioramacon** [irpepper/Smart-Mirror#1]
We need to determine the Linux Distro we'll be running on the Raspberry Pi. There are many options to choose from, and we need to pick on that will be highly customizable.

Some for the Raspberry Pi 2 (which can run more versions than the Raspberry Pi 1):
- Raspbian - The basic Raspberry Pi Distribution.
- Fedora 21 - Supposedly runs on the RP2, and seems to be more fully-featured.
- Ubuntu 15.04 Mate -  Designed to run on less powerful machines, might be a good choice.
- RiscOS - Seems to be pretty basic, might be too basic. Not sure at this point.

**Comment by irpepper** [comment]
I think Raspbian is fine for what we are planning. If not we can always change this later without much hassle. Our documentation needs to contain all commands required to run the mirror, such as libraries we downloaded and such. Ideally we will just write a script that will run them all for easy setup.

**Comment by melioramacon** [comment]
Yeah, if we could have it work "out of the box" if at all possible, that would be great.
