### ISSUE TITLE
Startup Animation

### ISSUE THREAD

**Issue by melioramacon** [irpepper/Smart-Mirror#10]

**Comment by irpepper** [comment]
Just like a simple light darting around the edge of the browser screen everytime the mirror wakes up. Maybe we can just do it on webpage refresh and make life easy.

**Comment by melioramacon** [comment]
From my research, it looks like it'll still boot with the original Raspberry Pi logo (and boot information), and then cut to the image / video.

Steps are as follows:
- Move video to Pi
- sudo apt-get install omxplayer
- cd /etc/init.d
- sudo wget -O asplashscreen http://goo.gl/sqDMT3
- sudo nano /etc/init.d/asplashscreen
- Change video source
- sudo nano /boot/cmdline.txt
- add "quiet" to end
- sudo chmod a+x /etc/ini.d/asplashscreen
- sudo insserv /etc/ini.d/asplashscreen
- sudo nano /etc/rc.local
- add "clear" right before exit 0 at end
- sudo reboot

Sources:
http://raspberrypi.stackexchange.com/questions/1214/how-to-add-custom-loading-screen
https://www.youtube.com/watch?v=IX4f3BWOwAc

**Comment by melioramacon** [comment]
Also, here's a thought for a splash image. With some work, I could make it animated to make it fancy.
![splash](https://cloud.githubusercontent.com/assets/7065579/12999820/fb91e8ae-d118-11e5-96db-bc6875722c88.png)

**Comment by melioramacon** [comment]
I've got this working as a static image currently.

**Comment by melioramacon** [comment]
Got this working with a video. Video hangs as OS loads...might need to add "loading" below the pudding logo or something.

**Comment by melioramacon** [comment]
Just so you can see it in action:

[A crappy video of it will be available here in a minute.](https://youtu.be/ihD_rEpPK4U)
