### ISSUE TITLE
Gather Parts

### ISSUE THREAD

**Issue by melioramacon** [irpepper/Smart-Mirror#12]
We need to gather all the parts. This list will be updated as we determine what we need.
- Raspberry Pi 1 or 2
- Photo cell (for sensing light)
- WiFi dongle
- Breadboard if we need to do any circuitry work
- Power Supply
- SD card (for OS)
- Motion Sensor
- Monitor
- HDMI Cable
- Frame
- Two-way mirror

The first 6 items are available as part of [this kit](https://www.adafruit.com/products/2380). It should be noted that the kit also comes with buttons and several other things that might be useful.

**Comment by irpepper** [comment]
I have everything on that list except:
- Photo Cell
- Motion Sensor
- Frame 
- Two way mirror

I had planned on just using some wood left over and my grandfather's shop and building the frame there to custom fit the monitor. So that is kind of marked off.

**Comment by melioramacon** [comment]
- Photo Cell [here](https://www.adafruit.com/products/161)

**Comment by melioramacon** [comment]
Also, do you have the 1 or 2? I have a RP1, so that would help a bit if we were working on the same board.

**Comment by irpepper** [comment]
All I know is that I don't have the one that came out like 6 months ago, so probably the 1. I think it is the model B+ of that series.

**Comment by melioramacon** [comment]
The Raspberry Pi 1 Model B+ came out in July 2014, and the Raspberry Pi 2 Model B came out in February 2015. It's a toss up. The only major difference is more processing power and memory, honestly.

**Comment by irpepper** [comment]
I'm fairly certain I have the model B+, but I've been wrong before.

**Comment by melioramacon** [comment]
Then we'll develop for the B+ unless proven otherwise.

**Comment by irpepper** [comment]
I've ordered the photo cell and motion sensor. I am going to check home depot for the mirror film.
