### ISSUE TITLE
Boot Raspberry Pi to Fullscreen Browser

### ISSUE THREAD

**Issue by melioramacon** [irpepper/Smart-Mirror#13]
This script also needs to launch XAMP or whatever server application we use.
Here's a good way of doing it:

http://blogs.wcode.org/2013/09/howto-boot-your-raspberry-pi-into-a-fullscreen-browser-kiosk/

**Comment by irpepper** [comment]
Not 100% on this but I think we can just add:
chromium-browser --kiosk www.google.com
to .bashrc and it will do what we want.

**Comment by melioramacon** [comment]
Working on this right now. Looks like chromium is not a valid option at the moment

**Comment by melioramacon** [comment]
Ok, so chromium isn't available (nor is chromium-browser). Iceweasel is _really_ slow and I'm having trouble running it in fullscreen from the command line. Midori and Luakit aren't running the CSS3 animations. Fun!

On a side note, I got it to display in profile.

I'm going to have to mull this one over for a bit.

**Comment by melioramacon** [comment]
Ok, switched the browser to kweb, because it has a kiosk mode. It's running the CSS3 animations (for the most part, I need to rewrite the ones for the welcome pages). Animations are a bit choppy and I'm still trying to get it to launch at boot. Progress.

**Comment by melioramacon** [comment]
Figured it out! This all has to happen _after_ we've set up a LAMP server on the pi.

Create a new file: /home/pi/.xsession

`#!/bin/bash
kweb -KJEHCUA+-zbhrqfpoklgtjneduwxy http://localhost`

This boots **DIRECTLY** to the browser...and there's no way to get out of it.
Use CTRL-ALT-F1 to get back to terminal, and CTRL-ALT-F7 (from the terminal) to get back to X.
