### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by melioramacon** [irpepper/Smart-Mirror#18]
We need to have a backend that the user can configure. We don't necessarily want them to have to configure Linux, but we want them to be able to configure their mirror, so to speak.

This would include things like:
- What RSS feed(s) they want
- User name
- Other preferences, etc.

**Comment by irpepper** [comment]
If we do this on a separate URL, the user should never have to use the Airplay mouse.

**Comment by melioramacon** [comment]
Or we could use the Airplay mouse stuff as more of an "on-the-fly" system. Use the backend to customize, but they'll need a way of interacting with the machine.

**Comment by melioramacon** [comment]
Backend is entirely functional, but I'm thinking that I may just redirect the user to welcome2.html because, well, it does the same thing. Closed.
