### ISSUE TITLE
AirPlay Mouse Support

### ISSUE THREAD

**Issue by melioramacon** [irpepper/Smart-Mirror#9]
We need to be implement this for iOS and Android users to make it universal. This will allow the user to configure the device on the fly.

**Comment by irpepper** [comment]
Airport has a linux server install. I don't know how easy it is to setup and if we need to do anything special after we install it. Hopefully it is plug n play.

**Comment by melioramacon** [comment]
This might be a better option:

[RemotePi](http://remotepi.io/)

**Comment by melioramacon** [comment]
Confirmed. This works. It's behind a $1.99 paywall, though.

**Comment by melioramacon** [comment]
I'm going to close this unless we find a better option. It's pretty cool, though there's a little lag.
